name: events

on:
    push:
        branches:
            - main
            - '!develop'
        paths:
            - "./src"
jobs:
    build:
        name: Build Project
        runs-on: ubuntu-latest
        steps:
            - run : echo "Job done"