name: spacial exploring

on: push

jobs:
  explore:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mission:
          - nom: Mars
            equipements: "Rover, Combinaison spatiale"
            duree: "7 mois"
            activite: "Analyse des roches"
            destination: "planete"
            emoji: "🚀"
          - nom: Lune
            equipements: "Module lunaire, Combinaison spatiale"
            duree: "3 jours"
            activite: "Collecte d'échantillons"
            destination: "satellite"
            emoji: "🌕"
          - nom: Venus
            equipements: "Sonde atmosphérique, Instruments scientifiques"
            duree: "5 mois"
            activite: "Analyse atmosphérique"
            destination: "planete"
            emoji: "🪐"
    name: Exploration - ${{ matrix.mission.nom }}
    steps:
      - run: |
          echo "### Mission Logbook - ${{ matrix.mission.nom }} ${{ matrix.mission.emoji }}"
          echo ""
          echo "| 🔖 Mission | 🧰 Équipements | ⏳ Durée | 🧪 Activité | 🌍 Destination |"
          echo "|------------|----------------|----------|-------------|----------------|"
          echo "| ${{ matrix.mission.nom }} | ${{ matrix.mission.equipements }} | ${{ matrix.mission.duree }} | ${{ matrix.mission.activite }} | ${{ matrix.mission.destination }} |"
          echo ""
          echo "🎯 **Mission ${{ matrix.mission.nom }}** complete ✅"

  demandes_president:
    runs-on: ubuntu-latest
    needs: explore
    strategy:
      matrix:
        include:
          - nom: Mars
            emoji: "🚀"
            equipement_special: "🍔 Space Burger"
            commentaire: "Pour maintenir le moral de l'équipage"
          - nom: Lune
            emoji: "🌕"
            equipement_special: "🔭 Télescope pour observer les aliens"
            commentaire: "Parce que les aliens existent, c'est sûr !"
          - nom: Venus
            emoji: "🪐"
    name: Demandes Présidentielles - ${{ matrix.nom }}
    steps:
      - run: |
          echo "### 📝 Demande présidentielle pour ${{ matrix.nom }} ${{ matrix.emoji }}"
          echo ""
          echo "| 🎁 Équipement spécial | 💬 Commentaire |"
          echo "|------------------------|----------------|"
          echo "| ${{ matrix.equipement_special || 'Pas besoin' }} | ${{ matrix.commentaire || 'Aucun commentaire' }} |"
          echo ""
          echo "👨‍✈️ Instructions présidentielles traitées ✅"
