name: Matrix
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20, 22]
        include:
          - os: macos-latest
            node-version: 24
          - os: windows-latest
            node-version: 24
          - os: windows-latest
            node-version: 22
            architecture: x86_64
    steps:
      - run: |
          echo "Running ${{ matrix.os }} with node ${{ matrix.node-version }}"
          echo "Architecture: ${{ matrix.architecture || 'default' }}"