name: Matrix
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [20, 22]
    steps:
      - run: echo "Running ${{ matrix.os }} with node ${{ matrix.node-version }}"