name: PizzaCI - Express

on:
  workflow_dispatch:
    inputs:
      nom_client:
        description: "Nom du client"
        required: true
      pizzas:
        description: |
          Liste des pizzas au format JSON. Attention aux points importants:
          - Utilisez des guillemets doubles
          - Entourez la liste avec []
          Exemple: ["margherita","reine","calzone"]
        required: true

jobs:
  reception-commande:
    runs-on: ubuntu-latest
    outputs:
      pizzas: ${{ steps.extract.outputs.pizzas }}
    steps:
      - name: Message d'accueil
        run: echo "🍕 Bienvenue ${{ github.event.inputs.nom_client }} chez PizzaCI - Express !"

      - name: Confirmation de la commande
        id: extract
        run: |
          echo "📦 Commande reçue pour les pizzas : ${{ github.event.inputs.pizzas }}"
          echo "pizzas=${{ github.event.inputs.pizzas }}" >> $GITHUB_OUTPUT

  cuisine:
    runs-on: ubuntu-latest
    needs: reception-commande
    strategy:
      matrix:
        pizza: ${{ fromJSON(needs.reception-commande.outputs.pizzas) }}
        taille: ["L", "XL"]
        include:
          - pizza: "choco-banana"
            taille: "L"
    steps:
      - name: Préparation de la pizza
        run: echo "👨‍🍳 Préparation de la pizza ${{ matrix.pizza }} taille ${{ matrix.taille }}..."

  livraison:
    runs-on: ubuntu-latest
    needs: cuisine
    concurrency:
      group: livraison
      cancel-in-progress: true
    steps:
      - name: Préparation de la livraison
        run: echo "🚚 Livraison en cours pour ${{ github.event.inputs.nom_client }}"

      - name: Récapitulatif des pizzas livrées
        run: |
          echo "📦 Pizzas en cours de livraison : ${{ github.event.inputs.pizzas }}"

  reclamation:
    runs-on: ubuntu-latest
    needs: livraison
    permissions:
      issues: write
    steps:
      - name: Checkout du dépôt
        uses: actions/checkout@v4

      - name: Création de l'issue de réclamation (simulation)
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh issue create --title "🧾 Réclamation potentielle pour la commande de ${{ github.event.inputs.nom_client }}" \
            --body "Merci de vérifier que la livraison correspond bien aux attentes. Pizzas commandées : ${{ github.event.inputs.pizzas }}"
